name: 'gha-inputs-validation'
description: 'Validate workflow inputs'
inputs:
  workflow_inputs:
    description: 'The workflow inputs'
    required: true
    default: '{}'
  cel_expressions:
    description: 'The validation in CEL format'
    required: true
runs:
  using: 'node20'
  main: 'index.js'