name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Test validation
        uses: ./
        with:
          schema: email.contains("@")
          inputs: '{"email": "josecarlos.chavez@owasp.org"}'
