name: Test action

on:
  workflow_dispatch:
    inputs:
      email:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Run action
        uses: ./
        with:
          workflow_inputs: ${{ inputs }}
          cel_expressions: |
            '1==1'
            '2==2'
