name: CI

on:
  workflow_dispatch:
    inputs:
      email:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Run action
        uses: ./
        with:
          inputs: ${{ inputs }}
